import type { Email, QuantumKey, QKDLink, ActivityEvent, SecurityMetric, User } from './types';

export const mockCurrentUser: User = {
  id: 'USR-7A3F-92B1',
  email: 'arjun.mehta@isro.gov.in',
  name: 'Arjun Mehta',
  organization: 'ISRO — Space Applications Centre',
  role: 'Mission Scientist',
  avatarColor: 'from-quantum-500 to-accent-600',
  keyId: 'KID-7A3F92B1',
  registeredAt: '2026-08-12T09:14:00Z',
};

export const mockKeys: QuantumKey[] = [
  {
    id: 'KEY-MLKEM-7A3F',
    algorithm: 'ML-KEM-768',
    status: 'active',
    fingerprint: '4F2A 8B91 C3D7 E5F0 1A2B 3C4D 5E6F 7081',
    createdAt: '2026-08-12T09:14:00Z',
    expiresAt: '2026-11-12T09:14:00Z',
    keySize: '1184 bytes',
    purpose: 'encapsulation',
    rotations: 2,
    publicKeyPreview: 'a3f7b2c8e4d901f5b6a7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9',
  },
  {
    id: 'KEY-MLDSA-7A3F',
    algorithm: 'ML-DSA-65',
    status: 'active',
    fingerprint: '9E1D 4C2A 7F8B 3D60 5E4F 6A7B 8C9D 0E1F',
    createdAt: '2026-08-12T09:14:00Z',
    expiresAt: '2026-11-12T09:14:00Z',
    keySize: '1952 bytes',
    purpose: 'signature',
    rotations: 1,
    publicKeyPreview: 'd1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2',
  },
  {
    id: 'KEY-AES-7A3F',
    algorithm: 'AES-256-GCM',
    status: 'active',
    fingerprint: 'B5C7 D9E1 F3A5 2746 89AB CDEF 0123 4567',
    createdAt: '2026-08-19T07:00:00Z',
    expiresAt: '2026-08-19T19:00:00Z',
    keySize: '32 bytes',
    purpose: 'symmetric',
    rotations: 14,
    publicKeyPreview: '7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8',
  },
  {
    id: 'KEY-HYBRID-7A3F',
    algorithm: 'Hybrid',
    status: 'expiring',
    fingerprint: '1A2B 3C4D 5E6F 7081 9A2B 3C4D 5E6F 7081',
    createdAt: '2026-07-01T00:00:00Z',
    expiresAt: '2026-08-22T00:00:00Z',
    keySize: '3136 bytes',
    purpose: 'hybrid',
    rotations: 3,
    publicKeyPreview: 'f5e4d3c2b1a0f9e8d7c6b5a4f3e2d1c0b9a8f7e6d5c4b3a2f1e0d9c8b7a6f5e4',
  },
];

export const mockQKDLinks: QKDLink[] = [
  {
    id: 'QKD-LINK-001',
    peer: 'priya.sharma@isro.gov.in',
    peerNode: 'SAC-Node-B',
    status: 'connected',
    keyRate: 1.2,
    qber: 1.8,
    distance: 12,
    protocol: 'BB84',
    establishedAt: '2026-08-19T06:42:00Z',
    keysDistributed: 8473,
  },
  {
    id: 'QKD-LINK-002',
    peer: 'vikram.rao@isro.gov.in',
    peerNode: 'SAC-Node-C',
    status: 'connected',
    keyRate: 0.9,
    qber: 2.3,
    distance: 28,
    protocol: 'Decoy-State BB84',
    establishedAt: '2026-08-19T05:18:00Z',
    keysDistributed: 5291,
  },
  {
    id: 'QKD-LINK-003',
    peer: 'external@drdo.gov.in',
    peerNode: 'DRDO-Node-A',
    status: 'syncing',
    keyRate: 0.4,
    qber: 4.1,
    distance: 45,
    protocol: 'E91',
    establishedAt: '2026-08-19T08:01:00Z',
    keysDistributed: 1284,
  },
  {
    id: 'QKD-LINK-004',
    peer: 'archive@isro.gov.in',
    peerNode: 'Archive-Vault',
    status: 'degraded',
    keyRate: 0.1,
    qber: 6.8,
    distance: 52,
    protocol: 'BB84',
    establishedAt: '2026-08-18T14:22:00Z',
    keysDistributed: 842,
  },
];

export const mockEmails: Email[] = [
  {
    id: 'EM-001',
    from: 'priya.sharma@isro.gov.in',
    fromName: 'Priya Sharma',
    to: 'arjun.mehta@isro.gov.in',
    subject: 'Re: Quantum Channel Calibration Report — SAC-Node-B',
    preview: 'The BB84 link calibration is complete. QBER has stabilized at 1.8% across the 12km fiber stretch...',
    body: `Hi Arjun,\n\nThe BB84 link calibration is complete. QBER has stabilized at 1.8% across the 12km fiber stretch between SAC-Node-A and SAC-Node-B, well within the 11% security threshold.\n\nKey generation rate is holding steady at 1.2 kbps. I've attached the photon detection statistics and the sifted key reconciliation log.\n\nOne note: we're seeing slightly elevated error rates during peak sunlight hours (14:00–16:00 IST), likely due to thermal expansion in the fiber casing. Recommend scheduling high-priority key exchanges outside that window.\n\nThe attached files are encrypted with your ML-KEM-768 public key and signed with my ML-DSA-65 key. Please verify the signature before opening.\n\nBest regards,\nPriya`,
    date: '2026-08-19T08:42:00Z',
    read: false,
    starred: true,
    folder: 'inbox',
    encryption: 'quantum-secure',
    signed: true,
    signatureValid: true,
    attachments: [
      { id: 'ATT-1', name: 'bb84_calibration_report.enc', size: '2.4 MB', encrypted: true },
      { id: 'ATT-2', name: 'sifted_key_log.enc', size: '184 KB', encrypted: true },
    ],
    keyIdUsed: 'KEY-MLKEM-7A3F',
    signatureAlgorithm: 'ML-DSA-65',
  },
  {
    id: 'EM-002',
    from: 'vikram.rao@isro.gov.in',
    fromName: 'Vikram Rao',
    to: 'arjun.mehta@isro.gov.in',
    subject: 'Post-Quantum Migration Roadmap — Phase 2 Review',
    preview: 'Following the successful NIST FIPS 203/204 integration, here is the proposed timeline for Phase 2...',
    body: `Arjun,\n\nFollowing the successful NIST FIPS 203/204 integration, here is the proposed timeline for Phase 2 of the post-quantum migration:\n\n1. Q4 2026 — Replace all RSA-2048 key exchange with ML-KEM-768 across internal relay servers.\n2. Q1 2027 — Deploy ML-DSA-65 for all inter-agency communications (DRDO, DRDL).\n3. Q2 2027 — Hybrid mode (classical + PQC) during the transition window.\n4. Q3 2027 — Full PQC-only operation, deprecate classical algorithms.\n\nNeed your input on the hybrid transition window. The team is leaning toward a 90-day overlap.\n\nThe document is quantum-secured. Signature attached for integrity verification.\n\nVikram`,
    date: '2026-08-19T07:15:00Z',
    read: false,
    starred: false,
    folder: 'inbox',
    encryption: 'quantum-secure',
    signed: true,
    signatureValid: true,
    attachments: [
      { id: 'ATT-3', name: 'pqc_migration_roadmap.enc', size: '1.1 MB', encrypted: true },
    ],
    keyIdUsed: 'KEY-MLKEM-7A3F',
    signatureAlgorithm: 'ML-DSA-65',
  },
  {
    id: 'EM-003',
    from: 'external@drdo.gov.in',
    fromName: 'DRDO Secure Gateway',
    to: 'arjun.mehta@isro.gov.in',
    subject: 'Cross-Agency Key Exchange — E91 Protocol Handshake',
    preview: 'Initiating E91 entanglement-based QKD link between DRDO-Node-A and SAC-Node-A. Awaiting key confirmation...',
    body: `This is an automated message from the DRDO Secure Gateway.\n\nInitiating E91 entanglement-based QKD link between DRDO-Node-A and SAC-Node-A.\n\nBell inequality test result: S = 2.78 (threshold: >2.0) — entanglement confirmed.\nKey sifting in progress. Expected key rate: 0.4 kbps over 45km.\n\nPlease confirm key receipt on your Key Manager interface. This link will remain active for the next 72 hours for synchronous key exchange.\n\n— DRDO Secure Gateway Automated System`,
    date: '2026-08-19T06:30:00Z',
    read: true,
    starred: false,
    folder: 'inbox',
    encryption: 'post-quantum',
    signed: true,
    signatureValid: true,
    attachments: [],
    keyIdUsed: 'KEY-MLKEM-7A3F',
    signatureAlgorithm: 'ML-DSA-65',
  },
  {
    id: 'EM-004',
    from: 'mission.control@isro.gov.in',
    fromName: 'Mission Control',
    to: 'arjun.mehta@isro.gov.in',
    subject: 'Launch Window Coordinates — Classified',
    preview: 'ATTENTION: This message contains classified launch window data. Encrypted with quantum-derived key...',
    body: `CLASSIFIED — LEVEL 4\n\nRecipient: Arjun Mehta (USR-7A3F-92B1)\n\nThis message contains classified launch window coordinates for the upcoming PSLV-C59 mission.\n\nPayload encryption: AES-256-GCM with QKD-derived session key.\nKey encapsulation: ML-KEM-768 (FIPS 203).\nDigital signature: ML-DSA-65 (FIPS 204) — verified.\n\nLaunch window opens: 2026-09-14 06:12:43 IST\nLaunch window closes: 2026-09-14 06:38:21 IST\nPrimary payload: EOS-09 (Earth Observation Satellite)\n\nDo not forward. Do not print. This message will self-destruct from the key manager cache after 72 hours.\n\n— Mission Control, ISRO HQ`,
    date: '2026-08-18T22:00:00Z',
    read: true,
    starred: true,
    folder: 'inbox',
    encryption: 'quantum-secure',
    signed: true,
    signatureValid: true,
    attachments: [
      { id: 'ATT-4', name: 'launch_window_classified.enc', size: '512 KB', encrypted: true },
    ],
    keyIdUsed: 'KEY-MLKEM-7A3F',
    signatureAlgorithm: 'ML-DSA-65',
  },
  {
    id: 'EM-005',
    from: 'kavya.nair@isro.gov.in',
    fromName: 'Kavya Nair',
    to: 'arjun.mehta@isro.gov.in',
    subject: 'Threat Model Document — Harvest Now, Decrypt Later',
    preview: 'I have completed the threat model for the harvest-now-decrypt-later attack vector. Attaching the...',
    body: `Hi Arjun,\n\nI have completed the threat model for the harvest-now-decrypt-later attack vector.\n\nSummary of findings:\n- All RSA/ECC encrypted traffic intercepted today is vulnerable to future quantum decryption (Shor's algorithm).\n- Our QKD-PQC hybrid approach mitigates this: keys derived from quantum channels cannot be retroactively broken.\n- ML-KEM-768 provides 192-bit post-quantum security level.\n- ML-DSA-65 provides 192-bit post-quantum signature security.\n\nThe full threat model is attached and encrypted. Please review before the SIH final presentation.\n\nKavya`,
    date: '2026-08-18T16:45:00Z',
    read: true,
    starred: false,
    folder: 'inbox',
    encryption: 'quantum-secure',
    signed: true,
    signatureValid: true,
    attachments: [
      { id: 'ATT-5', name: 'threat_model_hndl.enc', size: '3.8 MB', encrypted: true },
    ],
    keyIdUsed: 'KEY-MLKEM-7A3F',
    signatureAlgorithm: 'ML-DSA-65',
  },
  {
    id: 'EM-006',
    from: 'security.audit@isro.gov.in',
    fromName: 'Security Audit System',
    to: 'arjun.mehta@isro.gov.in',
    subject: 'Weekly Security Audit — All Systems Quantum-Secure',
    preview: 'Automated security audit complete. 100% of communications using post-quantum cryptography. No vulnerabilities...',
    body: `AUTOMATED SECURITY AUDIT REPORT\nPeriod: 2026-08-12 to 2026-08-19\n\nSUMMARY\n- Total encrypted emails sent: 47\n- Total encrypted emails received: 89\n- Quantum-secured (QKD+PQC): 100%\n- Post-quantum only (PQC): 100%\n- Classical-only (RSA/ECC): 0%\n- Signature verification failures: 0\n- QBER anomalies detected: 0\n- Key rotation events: 14\n\nRESULT: ALL SYSTEMS QUANTUM-SECURE.\n\nNo vulnerabilities detected. All communications resistant to both classical and quantum adversaries.\n\n— Security Audit System`,
    date: '2026-08-18T10:00:00Z',
    read: true,
    starred: false,
    folder: 'inbox',
    encryption: 'post-quantum',
    signed: true,
    signatureValid: true,
    attachments: [],
    keyIdUsed: 'KEY-MLKEM-7A3F',
    signatureAlgorithm: 'ML-DSA-65',
  },
  {
    id: 'EM-007',
    from: 'rohit.gupta@isro.gov.in',
    fromName: 'Rohit Gupta',
    to: 'arjun.mehta@isro.gov.in',
    subject: 'liboqs Integration Test Results — NIST Test Vectors Pass',
    preview: 'All CRYSTALS-Kyber and CRYSTALS-Dilithium test vectors from NIST FIPS 203/204 pass successfully...',
    body: `Arjun,\n\nGreat news — all test vectors pass.\n\nCRYSTALS-Kyber (ML-KEM-768):\n- NIST FIPS 203 test vectors: 256/256 PASS\n- KeyGen: avg 0.3ms\n- Encaps: avg 0.4ms\n- Decaps: avg 0.4ms\n\nCRYSTALS-Dilithium (ML-DSA-65):\n- NIST FIPS 204 test vectors: 256/256 PASS\n- KeyGen: avg 0.5ms\n- Sign: avg 0.8ms\n- Verify: avg 1.1ms\n\nliboqs integration is solid. Ready for the SIH demo.\n\nRohit`,
    date: '2026-08-17T14:20:00Z',
    read: true,
    starred: false,
    folder: 'inbox',
    encryption: 'post-quantum',
    signed: false,
    signatureValid: false,
    attachments: [],
    keyIdUsed: 'KEY-MLKEM-7A3F',
    signatureAlgorithm: undefined,
  },
];

export const mockActivity: ActivityEvent[] = [
  { id: 'A1', type: 'qkd-link', message: 'QKD link established with SAC-Node-B (BB84, 1.2 kbps)', timestamp: '2026-08-19T08:42:00Z', severity: 'success' },
  { id: 'A2', type: 'email-received', message: 'Encrypted email received from Priya Sharma — signature verified', timestamp: '2026-08-19T08:42:00Z', severity: 'info' },
  { id: 'A3', type: 'key-rotated', message: 'AES-256-GCM session key rotated (rotation #14)', timestamp: '2026-08-19T07:00:00Z', severity: 'info' },
  { id: 'A4', type: 'qkd-link', message: 'E91 link syncing with DRDO-Node-A — Bell test S=2.78', timestamp: '2026-08-19T06:30:00Z', severity: 'success' },
  { id: 'A5', type: 'email-received', message: 'Classified message from Mission Control — quantum-secured', timestamp: '2026-08-18T22:00:00Z', severity: 'warning' },
  { id: 'A6', type: 'signature', message: 'ML-DSA-65 signature verified from Kavya Nair', timestamp: '2026-08-18T16:45:00Z', severity: 'info' },
  { id: 'A7', type: 'key-generated', message: 'Hybrid key generated (ML-KEM + X25519)', timestamp: '2026-08-18T09:00:00Z', severity: 'info' },
  { id: 'A8', type: 'auth', message: 'Mutual TLS authentication with Key Manager successful', timestamp: '2026-08-19T05:00:00Z', severity: 'success' },
];

export const mockSecurityMetrics: SecurityMetric[] = [
  { label: 'Post-Quantum Coverage', value: '100%', detail: 'All communications PQC-secured', trend: 'stable', icon: 'shield-check' },
  { label: 'Active QKD Links', value: '3 / 4', detail: '1 degraded, 0 disconnected', trend: 'up', icon: 'radio' },
  { label: 'Avg QBER', value: '2.1%', detail: 'Below 11% security threshold', trend: 'down', icon: 'activity' },
  { label: 'Keys Distributed', value: '15,890', detail: 'Across all quantum channels', trend: 'up', icon: 'key' },
  { label: 'Signature Verifications', value: '136', detail: '0 failures this week', trend: 'up', icon: 'badge-check' },
  { label: 'Key Rotations', value: '20', detail: 'Automated, on schedule', trend: 'stable', icon: 'refresh-cw' },
];
